= {Parallel Programming}


ifeval::["{project_name}" == "Parallel Programming"]
[.lead]
endif::[]

.DOCUMENTS
[.examp]
****

*What Is Parallel Computing?*

* Serial Computing *


Traditionally, software has been written for serial computation:

    A problem is broken into a discrete series of instructions
    Instructions are executed sequentially one after another
    Executed on a single processor
    Only one instruction may execute at any moment in time


* Parallel Computing *

In the simplest sense, parallel computing is the simultaneous use of multiple compute resources to solve a computational problem:

    A problem is broken into discrete parts that can be solved concurrently
    Each part is further broken down to a series of instructions
    Instructions from each part execute simultaneously on different processors
    An overall control/coordination mechanism is employed




****


.LINKS
****
xref:../assets/attachments/Session1_ParallelProgramming_Introduction.pdf[Session1 ParallelProgramming Introduction]

xref:../assets/attachments/Session2_ParallelProgramming_MPI.pdf[Session2 Parallel Programming MPI]

xref:../assets/attachments/Session3_ParallelProgramming_HybridOpenMP_MPI.pdf[Session3 Parallel Programming Hybrid]

xref:../assets/attachments/Session4_ParallelProgramming_Cuda.pdf[Session4 Parallel Programming CUDA]

xref:../assets/attachments/Session5_ParallelProgramming_HIP.pdf[Session5 Parallel Programming HIP]

xref:../assets/attachments/Session6_ParallelProgramming_Specx.pdf[Session6 Parallel Programming Specx]



****



.Coding with {feelpp} in {cpp} or {python}
[.examp]
****

Update 10:45

image::Session1_ParallelProgramming_Introduction.pdf[xref=#fragment,page=1]


****

